// Generated by CoffeeScript 1.6.2
(function() {
  var PATTERN;

  PATTERN = /^(\s*)## (.*)$/;

  module.exports = function(input, output, cb) {
    var comment_indent, comment_lines, flush_comments, readline;

    readline = require('readline').createInterface({
      input: input,
      output: output,
      terminal: false
    });
    comment_lines = [];
    comment_indent = void 0;
    flush_comments = function() {
      var comment_line, _i, _len;

      if (comment_lines.length === 1) {
        console.log("" + comment_indent + "### " + comment_lines[0] + " ###");
        return comment_lines = [];
      } else if (comment_lines.length > 1) {
        console.log("" + comment_indent + "###");
        for (_i = 0, _len = comment_lines.length; _i < _len; _i++) {
          comment_line = comment_lines[_i];
          console.log("" + comment_indent + comment_line);
        }
        console.log("" + comment_indent + "###");
        return comment_lines = [];
      }
    };
    readline.on('line', function(line) {
      var match;

      if (match = PATTERN.exec(line)) {
        if (match[1] === comment_indent) {
          return comment_lines.push(match[2]);
        } else {
          flush_comments();
          comment_indent = match[1];
          return comment_lines.push(match[2]);
        }
      } else if (comment_lines.length === 0) {
        return console.log(line);
      } else {
        flush_comments();
        return console.log(line);
      }
    });
    return readline.on('close', function() {
      flush_comments();
      return cb(null);
    });
  };

}).call(this);
